// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AdminWebApp.Server.Models;

public partial class AccountCategory
{
    public string AccountCategoryID { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string Avatar { get; set; }

    public bool? Status { get; set; }

    public int? Position { get; set; }

    public virtual ICollection<Account> Accounts { get; set; } = new List<Account>();
}