// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AdminWebApp.Server.Models;

public partial class Account
{
    public string Username { get; set; }

    public string Password { get; set; }

    public string FullName { get; set; }

    public string Avatar { get; set; }

    public string Email { get; set; }

    public string Mobile { get; set; }

    public string Address { get; set; }

    public bool? Gender { get; set; }

    public bool? Status { get; set; }

    public string PasswordEncodeKey { get; set; }

    public DateTime? PasswordUpdatedTime { get; set; }

    public DateTime? LastLoginTime { get; set; }

    public string RefreshToken { get; set; }

    public DateTime? RefreshTokenCreateTime { get; set; }

    public DateTime? CreateTime { get; set; }

    public DateTime? UpdateTime { get; set; }

    public string CreateBy { get; set; }

    public string AccountCategoryID { get; set; }

    public virtual AccountCategory AccountCategory { get; set; }

  
}